### PR TITLE
Added Nernst-Einstein approximation

### PR DESCRIPTION
**Pull request by arthurfl**

### CODE REVIEW

**Review by HakyungKwon-TRI — COMMENTED** [review]
Looks good, but can we make sure that the computed properties 1) are part of `get_all_properties` in analysis.py and 2) have associated tests?

**Comment by HakyungKwon-TRI** [comment]
Additionally, were you planning on adding other methods as well, or just the NE approx?

**Comment by arthurfl** [comment]
> Additionally, were you planning on adding other methods as well, or just the NE approx?

Just the NE approximation - another route would be implementing the Einstein's relation, but that poses serious concerns regarding the convergence of the conductivity, especially with limited time series (~50 ns is typically far from enough for polymer electrolytes). The same would apply for the Green-Kubo relation.

**Review by arashkhajeh-AMDD — DISMISSED** [review]
LGTM

**Comment by arthurfl** [comment]
I've updated the test data with Nernst-Einstein quantities (conductivity and transference number), as well as `get_all_properties()`. 

By the way, I've absolutely failed installing both the current version (through pip/conda) and the one of this branch (through docker), is that stable on other boxes?

**Comment by HakyungKwon-TRI** [comment]
@arthurfl please resolve the conflicts and merge. thank you!

**Comment by HakyungKwon-TRI** [comment]
@arthurfl it's failing some tests, one of which is @arashkhajeh-AMDD's test on population matrix?

**Review by arashkhajeh-AMDD — DISMISSED** [review]
Looks good to me!

**Review by arashkhajeh-AMDD — APPROVED** [review]
Great. Thanks!

**Pull request merged**
